# Exported from Render on 2024-05-21T09:28:21Z
services:
- type: web
  name: cla-api
  runtime: node
  repo: https://github.com/andy7d0/cla-api
  plan: free
  region: oregon
  buildCommand: npm install express axios body-parser uuid
  startCommand: node app.js
version: "1"
